name = "Slepians"
uuid = "97caf2bd-9cc0-4738-8821-c8999f46f3c9"
authors = ["Charlotte Haley <haleycharlotte@gmail.com>"]
version = "0.1.1"

[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FINUFFT = "d8beea63-0952-562e-9c6a-8e8ef7364055"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
KernelMatrices = "b172bcd2-82ed-11e9-108e-f9294c34b9e6"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PCHIPInterpolation = "afe20452-48d1-4729-9a8b-50fb251f06cd"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Arpack = "0.5"
FastGaussQuadrature = "0.4"
RecipesBase = "1"
FFTW = "1"
IterTools = "1"
FINUFFT = "2,3"
KrylovKit = "0.5"
SpecialFunctions = "2"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
